name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - werkzeug==2.0.1
  - pandas
  - bqplot
  - ipecharts
  - ipywidgets
  - numpy
  - plotly
  - dash
  - openssl
